require 'dotenv'
Dotenv.load

Vagrant.configure('2') do |config|
  # ansible provision
  config.vm.provision 'ansible' do |ansible|
    ansible.playbook = "provisioning/playbook.yml"
  end

  config.vm.box = 'azure'

  # use local ssh key to connect to remote vagrant box
  config.ssh.private_key_path = ENV['AZURE_SSH_PRIVATE_KEY']
  config.vm.provider :azure do |azure, override|

    # each of the below values will default to use the env vars named as below if not specified explicitly
    azure.tenant_id = ENV['AZURE_TENANT_ID']
    azure.client_id = ENV['AZURE_CLIENT_ID']
    azure.client_secret = ENV['AZURE_CLIENT_SECRET']
    azure.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']
    azure.location = ENV['AZURE_LOCATION']
    #azure.resource_group_name = ENV['AZURE_RESOURCE_GROUP_NAME']
  end
end
